name: 'Get Actions'
description: 'Get whatever github action happens on this Repo'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  payloadOp: # id of output
    description: 'The payload'
runs:
  using: 'node12'
  main: 'index.js'
